blank_issues_enabled: true
contact_links:
  - name: Security problem
    url: https://github.com/ThomasYates/drydock/security/advisories/new
    about: Please report these privately rather than opening an issue.
